### ISSUE TITLE
Unable to click or type into elements inside a Swipeable Card.

### ISSUE THREAD

**Issue by NwachukwuOfoma** [3DJakob/react-tinder-card#92] opened 2022-05-17 22:37 UTC
I discovered if I wrap a form around <TinderCard> tag I am unable to click or type into the input as the listener for the tag interprets all clicks in the area as a swipe. I am unsure whether if there is a solution such as changing the priorities of clicks of an area if someone could hit me up and update would love to know. But as far as I know yea all clicks in the card are interpreted as swipes so it is not possible to interact with an item inside a card.

**Comment by 3DJakob** [comment] 2022-05-26 09:47
Yes this is a issue that is not very easy to fix. There is s solution based around using onTouchStart https://github.com/3DJakob/react-tinder-card/issues/37#issuecomment-779389381. Im going to close this as it is a duplicate of https://github.com/3DJakob/react-tinder-card/issues/37 (and numerous other issue threads).

**Closed by 3DJakob** 2022-05-26 09:47 UTC
