### ISSUE TITLE
Can't swipe with my emulator

### ISSUE THREAD

**Issue by Vhouze** [3DJakob/react-tinder-card#48] opened 2021-04-29 06:50 UTC
Here you can see the example, I tried to click on it and nothing's happening, but when I click on the button, it swipes. Does anyone have the same problem ?

I didn't change the code except for TinderCard.js as react-spring told me that I needed to update 'interpolate' to 'to'.

https://gyazo.com/64382183c65df459e68e20ace1aec0b1

**Comment by 3DJakob** [comment] 2021-05-15 10:32
Hello! I am unsure why it does not work for you. Could you please try just downloading my https://github.com/3DJakob/react-native-tinder-card-demo test repository and running it as is? Works on both my simulator and my phone however the rotation in the simulator is a bit wonky.

**Comment by 3DJakob** [comment] 2022-12-19 13:57
While I could not reproduce this issue in the first place this should most definitely be fixed in https://github.com/3DJakob/react-tinder-card/pull/115.

**Closed by 3DJakob** 2022-12-19 13:57 UTC
