### ISSUE TITLE
[Question]: How to capture swipe moves before committing?

### ISSUE THREAD

**Issue by wiseaidev** [3DJakob/react-tinder-card#130] opened 2022-11-23 14:56 UTC
Hey @3DJakob, Thanks for the package. I am currently in the process of building the most advanced Tinder clone on earth using React, MUI, and Redux for the client. At the moment, I am wondering how to display "NOPE" and "LIKE", like the real one, when dragging a card, but before committing the swipe, know what I am saying? For now, [I built a custom logic](https://github.com/brave-date/brave-date/blob/355ead1e6e40edb6ac574922d195994409245e2a/src/components/MainContainer/index.js#L136-L171) for the buttons to display labels upon clicking. And it is working as expected. Take a look at the following demo:

https://user-images.githubusercontent.com/62179149/203576536-a45f5ccc-9f68-4459-90c0-f4d3aa45d194.mp4

For reference, you can check out:

- [The client repo](https://github.com/brave-date/brave-date).
- [recs page Demo](https://brave-date.netlify.app/app/recs).

Don't forget to smash that ⭐ button an odd number of times for future updates.
Regards.

**Comment by 3DJakob** [comment] 2022-11-25 00:04
Glad you like the package. This is a duplicate of https://github.com/3DJakob/react-tinder-card/issues/128 please refer to it.

**Closed by 3DJakob** 2022-11-25 00:04 UTC
