### ISSUE TITLE
React Native: Buttons on Card Unpressable

### ISSUE THREAD

**Issue by jerry-inc** [3DJakob/react-tinder-card#86] opened 2022-02-17 21:12 UTC
Hi,

Platform: React Native: ios & android
Issue: Buttons, Touchables, etc. inside the card do not fire oPpress actions

In the iOS simulator, only TouchableOpacity's onPressUp event was firing, however, when tried on a physical device that too didn't work. As a result, I had to move buttons outside the cards.

I have seen this issue reported before but for React only. so, any help regarding React Native would be much appreciated.

**Comment by nschucky** [comment] 2022-02-18 00:46
adding `onTouchStart={}` to the button did the job for me, hope it works for you.

https://github.com/3DJakob/react-tinder-card/issues/37

**Comment by 3DJakob** [comment] 2022-03-03 09:00
Duplicate of https://github.com/3DJakob/react-tinder-card/issues/37 as @nschucky pointed out. Closing this.

**Comment by jerry-inc** [comment] 2022-03-12 10:03
this issue is clearly not fixed. and yet you have closed this issue as well as [#37](https://github.com/3DJakob/react-tinder-card/issues/37). Furthermore, #37 is related to react while I opened this issue because it was also present in react-native.

anyway, I was just pointing out a bug. it will be great if it gets fixed.

@nschucky solution works on emulator only and doesn't work on iOS device

**Comment by c0rnonthec0bb** [comment] 2022-05-20 23:36
The above solution fixes _React_, not _React Native_.

**Comment by 3DJakob** [comment] 2022-05-21 12:37
Ok, my bad! Unfortunately, I cannot think of a simple solution to this right now. But I'm open to PRs to solve this issue. Just make sure to follow the [CONTRIBUTING.md](https://github.com/3DJakob/react-tinder-card/blob/master/CONTRIBUTING.md). The problem is that it is not completely straightforward how to capture swipes on the card unless they are on a button.

**Comment by noeckl** [comment] 2022-08-22 15:35
I only had to make a simple change in the source to make the card's content clickable. Swiping left and right as well as the buttons within the card work for me.

For this, I only had to change the following boolean return value to true:
```
onStartShouldSetPanResponderCapture: (evt, gestureState) => false,
```

I found the solution in this [thread](https://stackoverflow.com/a/50576784/7947994) that also contains some other solutions for this problem.

Hope it helps someone having this problem!

**Comment by 3DJakob** [comment] 2022-10-15 20:46
This has been fixed in https://github.com/3DJakob/react-tinder-card/pull/116 and released in 1.6.1 🎉

**Closed by 3DJakob** 2022-10-15 20:46 UTC

**Comment by JoeKauf** [comment] 2022-12-06 15:58
Would you be able to provide an example of how putting the className="pressable"? I'm experiencing the issue and can't quite seem to find where to put the className. Thanks!

**Comment by JoeKauf** [comment] 2022-12-06 16:27
> Would you be able to provide an example of how putting the className="pressable" on React Native? React Native uses styles also and some slightly different syntax functionality. Thanks!

onStartShouldSetPanResponderCapture: (evt, gestureState) => false, fixed it

**Comment by iamhitarth** [comment] 2022-12-21 08:56
> #116

@JoeKauf can you please provide more details on where you ended up using `onStartShouldSetPanResponderCapture: (evt, gestureState) => false`? 

I'm running into the same issue as you and unsure of where to use that function 🤔

**Comment by 3DJakob** [comment] 2022-12-21 17:44
> Would you be able to provide an example of how putting the className="pressable" on React Native? React Native uses styles also and some slightly different syntax functionality. Thanks!

As far as I’m aware this is a web only problem but I might be wrong. Otherwise I could look into creating a fix for native too possibly following @JoeKauf tip

**Comment by iamhitarth** [comment] 2022-12-21 21:22
Thanks @3DJakob - I can confirm that this is definitely still an issue on React Native. I'm on version 1.6.2 of react-tinder-card. Tried using `className="pressable"` on the `TouchableOpacity` component thats on the swipeable card and it didn't make any difference.

**Comment by BestLeader** [comment] 2022-12-22 07:29
@3DJakob @iamhitarth 

As per @noeckl, here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-tinder-card/index.native.js b/node_modules/react-tinder-card/index.native.js
index f443f57..f9d928c 100644
--- a/node_modules/react-tinder-card/index.native.js
+++ b/node_modules/react-tinder-card/index.native.js
@@ -154,10 +154,16 @@ const TinderCard = React.forwardRef(
       () =>
         PanResponder.create({
           // Ask to be the responder:
-          onStartShouldSetPanResponder: (evt, gestureState) => true,
-          onStartShouldSetPanResponderCapture: (evt, gestureState) => true,
-          onMoveShouldSetPanResponder: (evt, gestureState) => true,
-          onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,
+          onStartShouldSetPanResponder: (evt, gestureState) => false,
+          onStartShouldSetPanResponderCapture: (evt, gestureState) => false,
+          onMoveShouldSetPanResponder: (evt, gestureState) => {
+            const { dx, dy } = gestureState
+            return (dx > 2 || dx < -2 || dy > 2 || dy < -2)
+          },
+          onMoveShouldSetPanResponderCapture: (evt, gestureState) => {
+            const { dx, dy } = gestureState
+            return (dx > 2 || dx < -2 || dy > 2 || dy < -2)
+          },
 
           onPanResponderGrant: (evt, gestureState) => {
             // The gesture has started.
```

**Comment by iamhitarth** [comment] 2022-12-22 09:46
Ah so you guys ended up updating the source for `react-tinder-card` @BestLeader - good to know. Thank you! 😁

**Comment by azwinlam** [comment] 2023-03-07 06:24
> @3DJakob @iamhitarth
> 
> As per @noeckl, here is the diff that solved my problem:
> 
> ```diff
> diff --git a/node_modules/react-tinder-card/index.native.js b/node_modules/react-tinder-card/index.native.js
> index f443f57..f9d928c 100644
> --- a/node_modules/react-tinder-card/index.native.js
> +++ b/node_modules/react-tinder-card/index.native.js
> @@ -154,10 +154,16 @@ const TinderCard = React.forwardRef(
>        () =>
>          PanResponder.create({
>            // Ask to be the responder:
> -          onStartShouldSetPanResponder: (evt, gestureState) => true,
> -          onStartShouldSetPanResponderCapture: (evt, gestureState) => true,
> -          onMoveShouldSetPanResponder: (evt, gestureState) => true,
> -          onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,
> +          onStartShouldSetPanResponder: (evt, gestureState) => false,
> +          onStartShouldSetPanResponderCapture: (evt, gestureState) => false,
> +          onMoveShouldSetPanResponder: (evt, gestureState) => {
> +            const { dx, dy } = gestureState
> +            return (dx > 2 || dx < -2 || dy > 2 || dy < -2)
> +          },
> +          onMoveShouldSetPanResponderCapture: (evt, gestureState) => {
> +            const { dx, dy } = gestureState
> +            return (dx > 2 || dx < -2 || dy > 2 || dy < -2)
> +          },
>  
>            onPanResponderGrant: (evt, gestureState) => {
>              // The gesture has started.
> ```

I tried to copy and paste the changes into the file however dx, dy are not defined. Am I missing another section?

**Comment by azwinlam** [comment] 2023-03-07 06:26
-          onStartShouldSetPanResponder: (evt, gestureState) => true,
-          onStartShouldSetPanResponderCapture: (evt, gestureState) => true,

Setting the above two lines to false did solve my problem with onPress not triggering. May I ask what does the onMove code change?

**Comment by BestLeader** [comment] 2023-03-07 06:33
@azwinlam
On some physical devices, if your fingers move very slightly (and they usually do in a normal press), it triggers the onMove. This change makes it so that onMove is only triggered when the move is more pronounced.

**Comment by azwinlam** [comment] 2023-03-07 06:52
Thanks for the prompt reply! I'll see if I can extract dx dy from gestureState. At the moment, it's causing an error.

**Comment by BestLeader** [comment] 2023-03-07 06:55
@azwinlam 
You can use "patch-package" to patch the source.

**Comment by azwinlam** [comment] 2023-03-07 06:57
Yah, it's working great on the iOS simulator already. Rebuilding the apk to see if the patch-package sticks. Thanks

**Comment by azwinlam** [comment] 2023-03-10 10:01
To follow-up, patch package and rebuilding of the apk. The fix DID NOT enable button press in cards.

**Comment by xtrinch** [comment] 2023-03-10 10:32
@azwinlam The patch posted above worked for me

**Comment by azwinlam** [comment] 2023-03-20 05:03
It is working now on the rebuild. The above fixes work!

**Comment by 3DJakob** [comment] 2023-09-22 06:31
I have merged the PR by @BestLeader and it will be in the next version!
