### ISSUE TITLE
Error: window is not defined

### ISSUE THREAD

**Issue by CodeOne45** [3DJakob/react-tinder-card#125] opened 2022-11-11 20:25 UTC
Got this error when I updated to version 1.6.2

![image](https://user-images.githubusercontent.com/57890543/201425731-17a3d89c-9971-4b67-b477-7a3b0cb05894.png)

**Comment by 3DJakob** [comment] 2022-11-12 15:52
Are you running on next.js?

**Comment by CodeOne45** [comment] 2022-11-12 15:56
yes, I'm on: next 12.3.1, react 18.2.0

**Comment by 3DJakob** [comment] 2022-11-15 14:29
Hm, I have limited experience with next js but I'm pretty sure the window global does not exist there as it is server side. To help find a solution to this it would be great if you could provide a minimal reproducible example. Essentially just create a new next js app and copy the code from the tinder-card example app. https://github.com/3DJakob/react-tinder-card-demo

**Comment by CodeOne45** [comment] 2022-11-17 14:34
I was able to fix the issue by adding manualy in node module package this: 
![image](https://user-images.githubusercontent.com/57890543/202474224-f43a462a-4ea2-4566-ab56-5575b1bace29.png)

**Comment by CodeOne45** [comment] 2022-11-17 14:57
@3DJakob create a PR for this : https://github.com/3DJakob/react-tinder-card/pull/127

**Comment by christianholman** [comment] 2022-11-22 14:55
Alternatively, you can use the next dynamic import module to bypass the component being rendered on the server (which doesn't have window defined).

```typescript
import dynamic from "next/dynamic"
const TinderCard = dynamic(() => import('react-tinder-card'), {
  ssr: false
});
```

**Comment by CodeOne45** [comment] 2022-11-22 15:24
@christianholman this works, but break's programmatically swiping cards 😫

**Comment by Simoneth** [comment] 2022-11-22 18:21
> @christianholman this works, but break's programmatically swiping cards 😫

that's probably caused by some package conflict

**Comment by 3DJakob** [comment] 2022-11-25 00:06
I have a PR in the works that fixes this issue without breaking programmatically swiping cards. It will be released soon. https://github.com/3DJakob/react-tinder-card/tree/window-undefined-fix

**Comment by 3DJakob** [comment] 2022-11-25 00:08
I do however think @christianholman fix is probably the best though as it doesn't really make any sense to render this particular module on the server anyway.

**Comment by CodeOne45** [comment] 2022-11-28 10:57
yeah I made the changes mentioned by @christianholman but that make some issues on swiping: 
![image](https://user-images.githubusercontent.com/57890543/204261021-962d1b69-959a-4bdf-b5a6-29f8f76b0054.png)

**Comment by Johnrobmiller** [comment] 2022-12-18 01:17
Since the web-dev world has largely switched to SSR/SSG, it's a shame to occasionally see libraries that insist on doing calculations on the client side like this, make this library unusable to so many people

**Comment by Johnrobmiller** [comment] 2022-12-18 01:35
> Alternatively, you can use the next dynamic import module to bypass the component being rendered on the server (which doesn't have window defined).
> 
> ```ts
> import dynamic from "next/dynamic"
> const TinderCard = dynamic(() => import('react-tinder-card'), {
>   ssr: false
> });
> ```

When people use SSR or SSG frameworks like Next.js, they do this because they want to use SSR or SSG, so telling Next.js to not use SSR or SSG is a bad solution.

**Comment by CodeOne45** [comment] 2022-12-25 16:11
@3DJakob @Johnrobmiller any solution to this?

**Comment by hauchu1998** [comment] 2023-09-20 19:35
> I have a PR in the works that fixes this issue without breaking programmatically swiping cards. It will be released soon. https://github.com/3DJakob/react-tinder-card/tree/window-undefined-fix

Hi~ I wonder if this version is released?

**Comment by 3DJakob** [comment] 2023-09-22 06:19
I have merged this and it will be in the next release of react-tinder-card! I don't know for sure if it solves all the Next JS issues. I would need to make another testing repository using next to verify this but since the fix worked for some users I will release it for now.

**Comment by 3DJakob** [comment] 2023-11-07 07:56
Closing this as it seems the issue has been resolved but feel free to reopen if the problem persists.

**Closed by 3DJakob** 2023-11-07 07:56 UTC
