### ISSUE TITLE
Swipe Animation Error while unloading and loading the component

### ISSUE THREAD

**Issue by Rohitparakh** [3DJakob/react-tinder-card#32] opened 2020-12-22 13:49 UTC
When you swipe a card, then unload the component and load it again, the wrong card swipe animation is done when you do the first swipe using the buttons. Although, it is registered correctly in the array, the correct card is removed from the screen without a swipe and the card which is swiped incorrectly also doesn't exist.

**Comment by 3DJakob** [comment] 2020-12-24 11:47
Hi! I'm not sure why you would unload the component and load it again why are you doing that? Is this reproducible in the advanced live demo? https://3djakob.github.io/react-tinder-card-demo/ In that case could you specify the steps used in that demo to reproduce the problem. Otherwise take a look at the code in the demo repository. https://github.com/3DJakob/react-tinder-card-demo/blob/master/src/examples/Advanced.js

It is key that you do not trigger rerender on cards that are in motion that will cause graphical issues. This is something that I have solved in the demo repository. 

Hope that helps!

**Comment by Rohitparakh** [comment] 2020-12-25 14:03
> Hi! I'm not sure why you would unload the component and load it again why are you doing that? Is this reproducible in the advanced live demo? https://3djakob.github.io/react-tinder-card-demo/ In that case could you specify the steps used in that demo to reproduce the problem. Otherwise take a look at the code in the demo repository. https://github.com/3DJakob/react-tinder-card-demo/blob/master/src/examples/Advanced.js
> 
> It is key that you do not trigger rerender on cards that are in motion that will cause graphical issues. This is something that I have solved in the demo repository.
> 
> Hope that helps!

I am trying to create a "people you have liked" list. So, if I render that component and then render the tinder cards component, this issue exists. Also, when reloading he component. The buttons don't work and give an error "The function swipe() of null couldn't be read". 

This situation can be recreated in the advanced demo. Try swiping some cards in the advanced example, then toggle and switch to basic mode and switch back to advanced mode. Now, when you swipe the first card, the issue mentioned exists.

P.S: I am new to github. Kindly excuse mistakes, if any! Also, thankyou for creating such a wonderful package :)

**Comment by 3DJakob** [comment] 2021-02-16 11:21
Ok so if I have understood your problem correctly you want to:

1. Swipe cards
2. unmount component
3. go back to the stack without the already swiped cards

Here is how you fix this. Keep track of cards that are swiped away using the onSwipe listener. Once you mount the component again next time just **filter away the already swiped elements before mounting again**. The reason why the module works like this is to avoid re-rendering between swipes to increase performance and avoid canceling animations. This should probably solve your other issue as well as your other issue is caused by a missmatch in the data structure and graphical interface.

Try this out and let me know if you manage to fix it. If you need more help just say so and I can provide more concrete code examples.

**Comment by 3DJakob** [comment] 2022-10-15 21:21
Closing this as there has not been any activity for a long time after my proposed solution. Feel free to reopen in the future.

**Closed by 3DJakob** 2022-10-15 21:21 UTC
