### ISSUE TITLE
Touch to click appears disabled when button element (or other clickable element) is within TInderCard.

### ISSUE THREAD

**Issue by joe-oli** [3DJakob/react-tinder-card#55] opened 2021-06-23 20:15 UTC
Place a button as a child of TinderCard

```
<TinderCard
    name="etc"
>
<div className="card">
    <div>
        <button onClick={()=> { alert('hello World!') }}>Test BTN</button>
        {/* image */}
        {/* name */}
    </div>
</div>
</TinderCard>
```

Button click with mouse works; 
Button touch *on a touch-enabled device" does not work. It appears touch-to-click events are disabled within TInderCard ?!

DItto for other elements like IconButton or Link from React-Router !

The above is for Web / plain React version.

**Comment by jratana1** [comment] 2021-09-13 02:33
I could be wrong, but I think because the cards are draggable, the click event is prevented for touch.  Try adding a onTouchStart to the button.

**Comment by 3DJakob** [comment] 2021-10-05 10:16
The issue is that the `TinderCard` needs to use an `ev.preventDefault()` on the touch events in order to have good performance and most importantly prevent the user from scrolling the website while dragging the cards. The solution is to use the `onTouchEnd` event also.
```
<button onClick={()=> { alert('hello World!') }} onTouchEnd={() => alert('hello World!') }}>Test BTN</button>
```
Perhaps in the future, it would be useful to add prop `locked` to the `TinderCard` in order to prevent users from moving it while pressing buttons on the card.

**Closed by 3DJakob** 2021-10-05 10:16 UTC

**Comment by kelechukwu1** [comment] 2024-06-26 13:28
this solution does not work at all, I'm disappointed
